switching to EB

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -59,26 +59,35 @@ jobs:
       
     - name: Create or update Elastic Beanstalk environment
       run: |
-          aws elasticbeanstalk create-environment \
-            --application-name dune-backend \
-            --environment-name Dune-backend-env \
-            --solution-stack-name "64bit Amazon Linux 2 v4.0.0 running Docker" \
-            --option-settings file://eb-options.json
-          
-          echo "Waiting for environment to be ready..."
-          while true; do
-            STATUS=$(aws elasticbeanstalk describe-environments --environment-names Dune-backend-env --query "Environments[0].Status" --output text)
-            if [ "$STATUS" = "Ready" ]; then
-              echo "Environment is ready"
-              break
-            elif [ "$STATUS" = "Terminated" ]; then
-              echo "Environment creation failed. Cannot proceed."
-              exit 1
+            if [ "${{ env.ENV_STATUS }}" = "None" ]; then
+              echo "Creating new environment..."
+              aws elasticbeanstalk create-environment \
+                --application-name dune-backend \
+                --environment-name Dune-backend-env \
+                --solution-stack-name "${{ env.SOLUTION_STACK }}" \
+                --option-settings file://eb-options.json
             else
-              echo "Environment is $STATUS. Waiting..."
-              sleep 30
+              echo "Updating existing environment..."
+              aws elasticbeanstalk update-environment \
+                --environment-name Dune-backend-env \
+                --solution-stack-name "${{ env.SOLUTION_STACK }}" \
+                --option-settings file://eb-options.json
             fi
-          done
+            
+            echo "Waiting for environment to be ready..."
+            while true; do
+              STATUS=$(aws elasticbeanstalk describe-environments --environment-names Dune-backend-env --query "Environments[0].Status" --output text)
+              if [ "$STATUS" = "Ready" ]; then
+                echo "Environment is ready"
+                break
+              elif [ "$STATUS" = "Terminated" ]; then
+                echo "Environment update/creation failed. Cannot proceed."
+                exit 1
+              else
+                echo "Environment is $STATUS. Waiting..."
+                sleep 30
+              fi
+            done
       
     - name: Deploy to Elastic Beanstalk
       uses: einaregilsson/beanstalk-deploy@v21
